#!/usr/bin/env python3

import sys
sys.path.append("Class")
sys.path.append("Client-IA")
from OptionManager import OptionManager
from AI import AI
import numpy as np

if __name__ == '__main__':
    optManager = OptionManager()
    optManager.getParams()
    player = AI(optManager)
    player.run()
    os._exit(os.EX_OK)
